### ISSUE TITLE
Tensorboard Output for Top-1 Acc

### ISSUE THREAD

**Issue by andrewsx** [maple-research-lab/EnAET#2]
Hello,
In the test.log output under top1, the values don't seem to match up with the TensorBoard output for the Top1 graph in Accuracy. The Top1 graph on TensorBoard shows three lines (EMA-test-acc, Model test-acc and Train-acc). I'm assuming that the top1 values in the test.log should match up with the values in the Tensorboard for Model-test-acc. However, they seem to line up with EMA-test-acc instead.

My question is which one should be used to determine model accuracy on the test set? In the ablation experiment, EMA was removed, so is that the result as shown in tensorboard for Model-test-acc?

Thanks for clearing up any confusion :)

**Comment by wang3702** [comment]
I have replied you in the email.
1 I have described in my paper that we applied EMA in our paper, all our results are reported based on teacher model's performance. test.log records the teacher model performance, which agrees with the EMA-test in your tensorboard. For details of EMA, please check meanteacher paper.
2 Yes, in the ablation study, when we removed EMA, the Model-test will be recorded in the test.log. But please pay attention to the EMA mechanism, Model-test on this condition is not the same as the Model-test when we remove EMA to run it. Please use --use_ema command to control this.
If your question is resolved, please close the issue. If not, welcome to update your question on this issue.
