### ISSUE TITLE
BackBone Model

### ISSUE THREAD

**Issue by wjun0830** [maple-research-lab/EnAET#5]
Hi.
Thanks for your great work.

I was curious about how it works with other network backbones.
If you have experimented any cases such as using Resnet-18 or 34 etc.,

Can you share your work with us?

**Comment by wang3702** [comment]
Thanks for paying attention to our work!
Sorry, I did not have the experiments with Resnet-18, 34 backbone. But if you want, you can simply replace our model parts with the pytorch implementation of Resnet: https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py. I believe it should be easier to run our code with Resnet architecture.
